name: Build on Push
on: push

jobs:
  tests:
    name: Test Go Dep Vendor
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build Docker-image
      uses: "docker://docker/compose:1.24.1"
      with:
        args: >-
              up
              --build
              --force-recreate
              --exit-code-from
              dapp-fs-test dapp-fs-test